# Hassas dosya ve yol erişim engeli
# Git, env, wp, php, admin, webshell, kripto
location ~* /(\.git|\.env|\.htaccess|\.htpasswd|xmlrpc\.php|info\.php|adminer.*\.php|adminfuns\.php|wp-login\.php|wp-config\.php|bitcoind|monerod|ioxi.*\.php) {
    deny all;
    return 444;
}

# PHP uzantılarını engelle (Next.js uygulamalarında PHP yok)
location ~* \.php$ {
    deny all;
    return 444;
}

# Webshell tarama kalıplarını engelle
location ~* (500\.php|about\.php|class-t|classwithtostring|file\.php|index/function\.php) {
    deny all;
    return 444;
}
