# Sensitive file and path access restricted
# Git, env, wp, php, admin, webshell, crypto
location ~* /(\.git|\.env|\.htaccess|\.htpasswd|xmlrpc\.php|info\.php|adminer.*\.php|adminfuns\.php|wp-login\.php|wp-config\.php|bitcoind|monerod|ioxi.*\.php) {
    deny all;
    return 444;
}

# Block php extensions.
location ~* \.php$ {
    deny all;
    return 444;
}

# Webshell scan patterns
location ~* (500\.php|about\.php|class-t|classwithtostring|file\.php|index/function\.php) {
    deny all;
    return 444;
}
